Davidmotson.auto functions
google/generative-ai-android pull request #50
Opened 2024-02-01 18:11 UTC by davidmotson

DO NOT MERGE

2024-02-10 11:08 UTC, rlazo commented on generativeai/src/main/java/com/google/ai/client/generativeai/GenerativeModel.kt
> +    return when (declaration) {
This can be simpler if we push the parsing to the `*ParameterFunction` classes

2024-02-10 11:09 UTC, rlazo commented on generativeai/src/main/java/com/google/ai/client/generativeai/GenerativeModel.kt
> +  private fun <T> getParamOrThrow(param: FunctionParameter<T>, part: FunctionCallPart): T {
This could be an extension function for FunctionCallPart

2024-02-10 11:10 UTC, rlazo commented on generativeai/src/main/java/com/google/ai/client/generativeai/internal/util/conversions.kt
> +@BetaGenAiAPI
Is it needed for internal methods?

2024-02-10 11:11 UTC, rlazo commented on generativeai/src/main/java/com/google/ai/client/generativeai/type/FunctionDeclarations.kt
> +/*
This file can be simplified if instead of using builder classes, we go with function overloads. See https://github.com/google/generative-ai-android/pull/54 for an example implementation

2024-02-23 17:06 UTC, thatfiredev commented on generativeai/src/main/java/com/google/ai/client/generativeai/type/RequestOptions.kt
> +  val autoFunction: Boolean = true
Having a boolean default to `true` makes it seem like we're enforcing some type of behavior that should be optional to the developer. As a developer, I usually prefer that booleans default to `false` and I'll flip it to true if I need to change some behavior. (see similar threads on [StackOverflow](https://stackoverflow.com/a/14157372/5861618) and [YAQS (googlers-only)](https://yaqs.corp.google.com/eng/q/7514440696221138944#a1))

I think if we really want auto function to be the default behavior, we should consider changing the name of the flag so that it can default to false:
```suggestion
  val disableAutoFunction: Boolean = false
```

2024-03-06 21:47 UTC, daymxn requested changes
Read through a bit of it, will read through the rest later

2024-03-06 21:47 UTC, daymxn commented on generativeai/src/main/java/com/google/ai/client/generativeai/Chat.kt
> +    val tempHistory = LinkedList<Content>()
In Kotlin, we try not to use inherited classes for lists. You generally wanna use `List` and `MutableList` directly, as it's more straight forward to read (there's no cognitive overhead in thinking about implementation specific details).
```suggestion
    val tempHistory = mutableListOf<Content>()
```

2024-03-06 21:47 UTC, daymxn commented on generativeai/src/main/java/com/google/ai/client/generativeai/type/RequestOptions.kt
> + * @property disableAutoFunction if true, auto functions will not be automatically executed
Was this from the doc, or did you make this decision? Because isn't it a code smell to have antonyms in your variables?
```kotlin
disableAutoFunction = false
```
vs
```kotlin
autoFunction = true
```

2024-03-06 21:47 UTC, daymxn commented on generativeai/src/main/java/com/google/ai/client/generativeai/type/FunctionParameter.kt
> +class FunctionParameter<T>(val name: String, val description: String, val type: FunctionType<T>) {}
missing kdocs

2024-03-06 21:47 UTC, daymxn commented on generativeai/src/main/java/com/google/ai/client/generativeai/type/Type.kt
> +class FunctionType<T>(val name: String, val parse: (String?) -> T?) {
missing kdocs

2024-03-06 21:47 UTC, daymxn commented on generativeai/src/main/java/com/google/ai/client/generativeai/internal/util/conversions.kt
> +  val convertedParams = buildJsonObject {
My brain is a little off rn, but I feel like there's a cleaner way to do this

2024-03-06 21:47 UTC, daymxn commented on generativeai/src/main/java/com/google/ai/client/generativeai/Chat.kt
> +        }
This was a bit confusing to read, it'd probably be easier to read if the break cases were abstracted out to the same level

```suggestion
        if (responsePart !is FunctionCallPart) break
        if (model.requestOptions.disableAutoFunction) break

        val output = model.executeFunction(responsePart)
        prompt = Content("function", listOf(FunctionResponsePart(responsePart.name, output)))
```

2024-03-07 15:43 UTC, thatfiredev commented on generativeai/src/main/java/com/google/ai/client/generativeai/type/RequestOptions.kt
> + * @property disableAutoFunction if true, auto functions will not be automatically executed
This change originated from [my comment here](https://github.com/google/generative-ai-android/pull/50#discussion_r1500949553) - I think having a boolean defaulting to `true` is a bigger code smell (but that might just be me).

2024-03-08 17:28 UTC, daymxn commented on generativeai/src/main/java/com/google/ai/client/generativeai/type/RequestOptions.kt
> + * @property disableAutoFunction if true, auto functions will not be automatically executed
Hmm, I've never heard that before- but I actually sort of agree. I'm fine with this, as the implementation site isn't a double negative.

2024-03-09 00:47 UTC, thatfiredev commented on generativeai/src/main/java/com/google/ai/client/generativeai/type/RequestOptions.kt
> + * @property disableAutoFunction if true, auto functions will not be automatically executed
@davidmotson @daymxn I checked the Python implementation and auto function calling is [disabled by default](https://github.com/google/generative-ai-python/blob/4f1ea10a0cc40ce53c142d4878f4852bb1d05d1e/google/generativeai/generative_models.py#L358) over there.

It seems like that's [by design](http://go/genai-automatic-function-calling-2024:default). Should we revert back to `autoFunction = true` ?

Sorry for the back and forth.

2024-03-12 21:58 UTC, davidmotson commented on generativeai/src/main/java/com/google/ai/client/generativeai/type/FunctionParameter.kt
> +class FunctionParameter<T>(val name: String, val description: String, val type: FunctionType<T>) {}
Turns out this class is never used, deleting it and adding kdocs to ParameterDeclaration

2024-03-20 13:22 UTC, rlazo commented
We don't need to change the copyright date in the headers.

2024-03-20 19:03 UTC, rlazo reviewed
Are there any changes necessary in common? all modifications are in generativeai

2024-03-20 19:03 UTC, rlazo commented on generativeai-android-sample/app/src/main/kotlin/com/google/ai/sample/GenerativeAiViewModelFactory.kt
> +                        generationConfig = config,
Given the inconsistent behaviour handling the functions, IMO we should have a separate entry in the sample app for function calling. This will prevent the regular chat example from failing due to an unrelated issue.

2024-03-20 19:04 UTC, davidmotson commented on generativeai-android-sample/app/src/main/kotlin/com/google/ai/sample/GenerativeAiViewModelFactory.kt
> +                        generationConfig = config,
oh whoops, this was not an intended part of the commit. I was doing this for my own testing, please ignore.

2024-03-21 01:14 UTC, closed without merging